### ISSUE TITLE
Build on Mac OS X fails with message `Error response from daemon: Unknown instruction: TEXLIVE-BASE`

### ISSUE THREAD

**Issue by jakubtuchol** [mccahill/docker-rstudio#2]
I've attempted running the `build` script on Mac OS X, but the build fails with the following message:

```
Sending build context to Docker daemon 135.2 kB
Error response from daemon: Unknown instruction: TEXLIVE-BASE
```

I am building this on a Mid 2015 Macbook Pro running OS X El Capitan, and the following Docker version:
```
Docker version 1.13.0-rc3, build 4d92237
```

I will attempt building this on Ubuntu to determine if the same error is present.

**Comment by mccahill** [comment]
It should work on Ubuntu because that is where I build and run.
Specifically, Docker version 1.12.5, build 7392c3b
